spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

firebase.credentials=${FIREBASE_CREDENTIALS}
firebase.storage.bucket=${FIREBASE_STORAGE_BUCKET}

jwt.secret=classroomManagementSystemSecretKeyClassroom2026VeryLongKey
jwt.expiration=86400000