# /resource/application-dev.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

firebase.credentials=${FIREBASE_CREDENTIALS}
firebase.storage.bucket=${FIREBASE_STORAGE_BUCKET}


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

server.servlet.session.persistent=false